---
maven_major_version: 3
maven_version: 3.9.8
sonarqube_path: /opt/sonarqube
sonarqube_version: 9.5.0.56709
tomcat_major_version: 8
tomcat_version: 8.5.100
tomcat_path: /opt
artifactory_version: "7.59.23"