---
- name: Installer des dépendances nécessaires (si pas déjà installées)
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - software-properties-common
    - gnupg

- name: Télécharger la clé GPG du référentiel Jenkins et la placer dans /usr/share/keyrings/
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Ajouter le référentiel Jenkins à APT sources
  copy:
    dest: /etc/apt/sources.list.d/jenkins.list
    content: |
      deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
    mode: '0644'

- name: Mettre à jour la liste des paquets APT
  apt:
    update_cache: yes

- name: Installer Jenkins
  apt:
    name: jenkins
    state: present

- name: Démarrer et activer Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: true

- name: wait for jenkins to start
  wait_for:
    timeout: 10

- name: get jenkins default key
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword || echo "installed"
  register: jenkins_admin_key

- name: show jenkins default key
  debug: msg="{{jenkins_admin_key.stdout}}"